language: cpp

cache:
  - apt

branches:
  except:
    - /.*pp.eyor.*/

before_install:
  # we need a recent version of CMake
  # - sudo add-apt-repository -y ppa:andykimpe/cmake3
  # linux prereqisite packages
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget --no-check-certificate https://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xzvf cmake-3.2.3-Linux-x86_64.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=$PWD/cmake-3.2.3-Linux-x86_64/bin:$PATH; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq -y unixodbc-dev libmysqlclient-dev libsqlite3-dev; fi 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq -y g++-arm-linux-gnueabi g++-arm-linux-gnueabihf clang-3.5; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq -y sloccount cppcheck; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq -y g++-4.8; fi

services:
  - mongodb
  - redis-server
  - postgresql
  - mysql

addons:
  postgresql: "9.3"


notifications:
  slack: 
    rooms:
      - pocoproject:ItIUZvs8aJGyPdaKxIKMnS1t#travis

env:
  global: 
    TEST_NAME=""
    
before_script:
 - echo ${TEST_NAME}
 - chmod 755 ./travis/Linux/runtests.sh
 - chmod 755 ./travis/OSX/runtests.sh
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mysql -u root -e 'create database pocotestdb;'; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mysql --version; fi
 - if [ "$TRAVIS_OS_NAME" == "linux" ]; then postgres --version; fi
 - sqlite3 -version

matrix:
  fast_finish: true

  include:

    - env:    TEST_NAME="Linux gcc 4.6 (make) bundled"
      compiler: gcc
      script:
        - export CC="gcc"
        - export CXX="g++"
        - ./configure --everything && make -s -j2 && ./travis/Linux/runtests.sh
    

